services:
  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: shop_app
    depends_on:
      - database
    environment:
      DB_NAME: shopdb
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: database
      DB_PORT: 5432
    stdin_open: true 
    tty: true         
    command: python app.py  
    volumes:
      - .:/app  

volumes:
  postgres_data:
